nclude "main.h"
#include <stdio.h>

int main()
{
		int len_2 = 0, len_1 = 0;
			/* ===========> %c <=========== */
			// printf("----> CHAR CASES <----\n");
			// 	// printf("----------------------\n");
			// 	    // printf("Expected Output: \n");
			// 	    	// len_1 = printf("%yd\n");
			// 	    	    // printf("Current Output: \n");
			// 	    	    	// len_2 = print_f("%yd\n");
			// 	    	    		// printf("Expected length:    [%d]\n", len_1);
			// 	    	    			// printf("Current length:     [%d]\n", len_2);
			// 	    	    				// printf("----------------------\n");
			// 	    	    					// printf("----------------------\n");
			// 	    	    					    // printf("Expected Output: \n");
			// 	    	    					    	// len_1 = printf("%   yd\n");
			// 	    	    					    	    // printf("Current Output: \n");
			// 	    	    					    	    	// len_2 = print_f("%   yd\n");
			// 	    	    					    	    		// printf("Expected length:    [%d]\n", len_1);
			// 	    	    					    	    			// printf("Current length:     [%d]\n", len_2);
			// 	    	    					    	    				// printf("----------------------\n");
			// 	    	    					    	    					// printf("----------------------\n");
			// 	    	    					    	    					    // printf("Expected Output: \n");
			// 	    	    					    	    					    	// len_1 = printf("%     yd\n");
			// 	    	    					    	    					    	    // printf("Current Output: \n");
			// 	    	    					    	    					    	    	// len_2 = print_f("%     yd\n");
			// 	    	    					    	    					    	    		// printf("Expected length:    [%d]\n", len_1);
			// 	    	    					    	    					    	    			// printf("Current length:     [%d]\n", len_2);
			// 	    	    					    	    					    	    				// printf("----------------------\n");
			// 	    	    					    	    					    	    					// printf("----------------------\n");
			// 	    	    					    	    					    	    					    // printf("Expected Output: \n");
			// 	    	    					    	    					    	    					    	// len_1 = printf("%  yd\n");
			// 	    	    					    	    					    	    					    	    // printf("Current Output: \n");
			// 	    	    					    	    					    	    					    	    	// len_2 = print_f("%  yd\n");
			// 	    	    					    	    					    	    					    	    		// printf("Expected length:    [%d]\n", len_1);
			// 	    	    					    	    					    	    					    	    			// printf("Current length:     [%d]\n", len_2);
			// 	    	    					    	    					    	    					    	    				// printf("----------------------\n");
			// 	    	    					    	    					    	    					    	    					// printf("----------------------\n");
			// 	    	    					    	    					    	    					    	    						// printf("Expected output:    ");
			// 	    	    					    	    					    	    					    	    							// len_1 = printf("%k", "valid format");
			// 	    	    					    	    					    	    					    	    								// printf("\n");
			// 	    	    					    	    					    	    					    	    									// printf("Current output:     ");
			// 	    	    					    	    					    	    					    	    										// len_2 = print_f("%k", "valid format");
			// 	    	    					    	    					    	    					    	    											// printf("\n");
			// 	    	    					    	    					    	    					    	    												// printf("Expected length:    [%d]\n", len_1);
			// 	    	    					    	    					    	    					    	    													// printf("Current length:     [%d]\n", len_2);
			// 	    	    					    	    					    	    					    	    														// printf("----------------------\n");
			// 	    	    					    	    					    	    					    	    														    // printf("----------------------\n");
			// 	    	    					    	    					    	    					    	    														    	// printf("Expected output:    ");
			// 	    	    					    	    					    	    					    	    														    		// len_1 = printf("%  s", "valid format");
			// 	    	    					    	    					    	    					    	    														    			// printf("\n");
			// 	    	    					    	    					    	    					    	    														    				// printf("Current output:     ");
			// 	    	    					    	    					    	    					    	    														    					// len_2 = print_f("%  s", "valid format");
			// 	    	    					    	    					    	    					    	    														    						// printf("\n");
			// 	    	    					    	    					    	    					    	    														    							// printf("Expected length:    [%d]\n", len_1);
			// 	    	    					    	    					    	    					    	    														    								// printf("Current length:     [%d]\n", len_2);
			// 	    	    					    	    					    	    					    	    														    								    //  printf("--------------------------");
			// 	    	    					    	    					    	    					    	    														    								        // printf("--------------------------\n");
			// 	    	    					    	    					    	    					    	    														    								        	printf("Expected output:    ");
			// 	    	    					    	    					    	    					    	    														    								        		len_1 = printf("", "valid format");
			// 	    	    					    	    					    	    					    	    														    								        			printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        				printf("Current output:     ");
			// 	    	    					    	    					    	    					    	    														    								        					len_2 = print_f("", "valid format");
			// 	    	    					    	    					    	    					    	    														    								        						printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        							printf("Expected length:    [%d]\n", len_1);
			// 	    	    					    	    					    	    					    	    														    								        								printf("Current length:     [%d]\n", len_2);
			// 	    	    					    	    					    	    					    	    														    								        								    printf("--------------------------");
			// 	    	    					    	    					    	    					    	    														    								        								        printf("--------------------------\n");
			// 	    	    					    	    					    	    					    	    														    								        								        	// printf("Expected output:    ");
			// 	    	    					    	    					    	    					    	    														    								        								        		// len_1 = printf(NULL,NULL);
			// 	    	    					    	    					    	    					    	    														    								        								        			// printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        								        				// printf("Current output:     ");
			// 	    	    					    	    					    	    					    	    														    								        								        					// len_2 = print_f(NULL, NULL);
			// 	    	    					    	    					    	    					    	    														    								        								        						// printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        								        							// printf("Expected length:    [%d]\n", len_1);
			// 	    	    					    	    					    	    					    	    														    								        								        								// printf("Current length:     [%d]\n", len_2);
			// 	    	    					    	    					    	    					    	    														    								        								        								    // printf("--------------------------");
			// 	    	    					    	    					    	    					    	    														    								        								        								        // printf("--------------------------\n");
			// 	    	    					    	    					    	    					    	    														    								        								        								        	// printf("Expected output:    ");
			// 	    	    					    	    					    	    					    	    														    								        								        								        		// len_1 = printf("", "");
			// 	    	    					    	    					    	    					    	    														    								        								        								        			// printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        								        								        				// printf("Current output:     ");
			// 	    	    					    	    					    	    					    	    														    								        								        								        					// len_2 = print_f("", "");
			// 	    	    					    	    					    	    					    	    														    								        								        								        						// printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        								        								        							// printf("Expected length:    [%d]\n", len_1);
			// 	    	    					    	    					    	    					    	    														    								        								        								        								// printf("Current length:     [%d]\n", len_2);
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    // printf("--------------------------");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    	printf("Expected output:    ");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    		len_1 = printf(NULL, NULL);
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    			printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    				printf("Current output:     ");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    					len_2 = print_f(NULL, NULL);
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    						printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    							printf("Expected length:    [%d]\n", len_1);
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								printf("Current length:     [%d]\n", len_2);
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    printf("--------------------------");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    	printf("Expected output:    ");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    		len_1 = printf("%ys");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    			printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    				printf("Current output:     ");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    					len_2 = print_f(NULL);
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    						printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    							printf("Expected length:    [%d]\n", len_1);
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								printf("Current length:     [%d]\n", len_2);
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    printf("--------------------------");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    	printf("Expected output:    ");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    		len_1 = printf("css%ccs%scscscs", 'T', "Test");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    			printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    				printf("Current output:     \n");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    					len_2 = print_f("css%ccs%scscscs", 'T', "Test");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    						printf("\n");
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    							printf("Expected length:    [%d]\n", len_1);
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    								printf("Current length:     [%d]\n", len_2);
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    								    printf("--------------------------");
			//
			//
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    								        return 0;
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    								        }
			// 	    	    					    	    					    	    					    	    														    								        								        								        								    								    								    								        	
